name: bigagent
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+14

environment:
  sdk: 3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1
  flutter_svg: 2.0.17
  dio: 5.7.0
  flutter_secure_storage: 9.2.2
  flutter_dotenv: 5.1.0
  go_router: 14.6.2
  riverpod: 2.6.1
  solana: 0.31.0
  cached_network_image: 3.4.1
  web_socket_channel: 2.4.0
  flutter_markdown: 0.7.5
  # in_app_purchase: 3.2.1
  url_launcher: 6.3.1
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0
  riverpod_generator: 2.6.3
  build_runner: 2.4.13
  custom_lint: 0.7.0
  riverpod_lint: 2.6.3

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - .env

  fonts:
    - family: AvenirNextLTPro
      fonts:
        - asset: assets/fonts/avenir_pro_regular.otf
    - family: AvenirLTStd
      fonts:
        - asset: assets/fonts/avenir_lt_std_medium.otf
